from pathlib import Path
from html import escape

ROOT = Path(__file__).parent
EMAIL = '50shadesofscience@gmail.com'
NAV = [
    ('Science', 'science.html'), ('Videos', 'videos.html'),
    ('Schools', 'school-programmes.html'), ('Future Scientists', 'future-scientists.html'),
    ('CSR & Partnerships', 'csr-partnerships.html'), ('About', 'about.html'),
    ('Research', 'research.html'),
]

def link(label, href, cls='text-link'):
    return f'<a class="{cls}" href="{href}">{label}<span aria-hidden="true"> ↗</span></a>'

def eyebrow(text):
    return f'<p class="eyebrow">{text}</p>'

def intro(kicker, title, deck):
    return f'<header class="page-intro wrap">{eyebrow(kicker)}<h1>{title}</h1><p class="deck">{deck}</p></header>'

def section(kicker, title, body, extra=''):
    return f'<section class="section wrap"><div class="section-heading">{eyebrow(kicker)}<h2>{title}</h2></div><div class="section-body">{body}{extra}</div></section>'

def card(kicker, title, copy, href=None, image=None):
    img = f'<img src="{image}" alt="" loading="lazy">' if image else ''
    more = link('Explore', href) if href else ''
    return f'<article class="card">{img}<div class="card-copy">{eyebrow(kicker)}<h3>{title}</h3><p>{copy}</p>{more}</div></article>'

def page(key, title, description, body):
    items = ''.join(f'<a href="{href}"{(" aria-current=\"page\"" if href == key else "")}>{label}</a>' for label, href in NAV)
    schema = '{"@context":"https://schema.org","@type":"Organization","name":"50 Shades of Science","description":"Independent science communication through talks, videos, and school programmes.","email":"mailto:50shadesofscience@gmail.com","sameAs":["https://www.instagram.com/50_shades_of_science/"]}'
    canonical = 'https://supriyosaha1.github.io/50-shades-of-science/' + ('' if key == 'index.html' else key)
    html = f'''<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>{escape(title)} | 50 Shades of Science</title><meta name="description" content="{escape(description, quote=True)}">
<meta name="theme-color" content="#f5f7f4"><link rel="canonical" href="{canonical}"><meta property="og:type" content="website"><meta property="og:url" content="{canonical}"><meta property="og:title" content="{escape(title, quote=True)} | 50 Shades of Science"><meta property="og:description" content="{escape(description, quote=True)}"><meta property="og:image" content="https://supriyosaha1.github.io/50-shades-of-science/assets/media/icecube-dawn.webp"><meta name="twitter:card" content="summary_large_image">
<link rel="icon" href="assets/favicon.svg" type="image/svg+xml"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700;800&family=IBM+Plex+Mono:wght@400;500;600&display=swap" rel="stylesheet"><link rel="stylesheet" href="assets/css/site-v2.css"><script type="application/ld+json">{schema}</script>
<script defer src="assets/js/site.js"></script></head>
<body><a class="skip" href="#main">Skip to content</a>
<header class="site-header"><div class="wrap header-inner"><a class="wordmark" href="index.html" aria-label="50 Shades of Science home"><span class="wordmark-number">50</span><span>SHADES OF<br>SCIENCE</span></a><button class="menu-button" type="button" aria-controls="site-nav" aria-expanded="false">Menu <span aria-hidden="true">☰</span></button><nav id="site-nav" aria-label="Main navigation">{items}<a class="nav-contact" href="contact.html">Book a session <span aria-hidden="true">↗</span></a></nav></div></header>
<main id="main">{body}</main>
<footer class="site-footer"><div class="wrap footer-top"><div><a class="footer-brand" href="index.html">50 Shades of Science</a><p>Curiosity belongs everywhere.</p></div><div class="footer-links"><a href="school-programmes.html">For schools</a><a href="csr-partnerships.html">For partners</a><a href="videos.html">Watch</a><a href="about.html">About</a></div><div class="footer-links"><a href="mailto:{EMAIL}">{EMAIL}</a><a href="https://www.instagram.com/50_shades_of_science/" target="_blank" rel="noopener noreferrer">Instagram ↗</a></div></div><div class="wrap footer-bottom"><small>© 2026 50 Shades of Science · Independent science communication</small><a href="#main">Back to top ↑</a></div></footer></body></html>'''
    (ROOT / key).write_text(html, encoding='utf-8')

home = '''<section class="hero wrap"><div class="hero-copy">'''+eyebrow('SCIENCE COMMUNICATION · INDIA')+'''<h1>Science is for <em>everyone.</em></h1><p class="hero-deck">Ideas that change how we see the world should be clear, exciting, and within reach. We bring research to life through films, talks, and learning experiences.</p><div class="actions"><a class="button" href="school-programmes.html">Explore school programmes ↗</a><a class="button secondary" href="videos.html">Watch our films ↗</a></div><div class="hero-note"><span>Founded by Supriyo Saha</span><span>PhD researcher in cosmology · TIFR Mumbai</span></div></div><figure class="hero-photo"><img src="assets/images/photos/bar-talk-speaker.webp" alt="Supriyo Saha speaking at a public science event" fetchpriority="high"><figcaption>A public science talk</figcaption></figure></section>
<div class="wrap strip"><span>01 / Clear science</span><span>02 / Real questions</span><span>03 / More curious minds</span></div>
''' + section('THE IDEA', 'The wonder survives the explanation.', '<p>Science can be rigorous and welcoming at the same time. We translate complex discoveries into stories people can question, remember, and use.</p><p>From the early universe to the brain, our work follows curiosity wherever it leads.</p>'+link('What we explore', 'science.html')) + '''<section class="section-wide tint"><div class="wrap"><div class="section-heading">'''+eyebrow('WATCH & DISCOVER')+'''<h2>Big ideas, made visible.</h2><p>Short films and visual explainers built around one good question at a time.</p></div><div class="feature-grid">'''+card('2026 NOBEL PHYSICS · VIDEO', 'How do you catch a ghost particle?', 'Travel beneath the Antarctic ice and see how IceCube detects neutrinos.', 'videos.html#icecube', 'assets/media/icecube.webp')+card('2026 NOBEL MEDICINE · VIDEO', 'What if light could control cells?', 'A visual introduction to optogenetics and the precise questions it lets researchers ask.', 'videos.html#optogenetics', 'assets/media/optogenetics.webp')+'''</div></div></section>
<section class="section wrap"><div class="section-heading">'''+eyebrow('WAYS TO WORK TOGETHER')+'''<h2>Make room for the question.</h2></div><div class="three-grid">'''+card('01 / EDUCATION', 'School programmes', 'Talks and workshops that help students connect ideas to evidence.', 'school-programmes.html')+card('02 / LONG-TERM LEARNING', 'Future Scientists', 'A programme vision for learning to think and investigate like a scientist.', 'future-scientists.html')+card('03 / SCALE & ACCESS', 'CSR partnerships', 'Design a measurable science engagement pilot with schools and communities.', 'csr-partnerships.html')+'''</div></section>
<section class="quote-band"><div class="wrap"><blockquote>“The best science question is the one that makes you look at the familiar world differently.”</blockquote><p>— 50 Shades of Science</p></div></section>
<section class="section wrap closing"><div>'''+eyebrow('START A CONVERSATION')+'''<h2>Bring science into your room.</h2></div><div><p>Planning a school visit, a public event, or a partnership? Tell us what you have in mind.</p>'''+link('Enquire or book', 'contact.html', 'button')+'''</div></section>'''
home = home.replace('Science is for <em>everyone.</em>', 'Make sense of <em>everything.</em>')
home = home.replace('Ideas that change how we see the world should be clear, exciting, and within reach. We bring research to life through films, talks, and learning experiences.', 'Real science. Clear stories. A more curious way to see the world. Explore films, live talks, and learning experiences built around the questions that matter.')
home = home.replace('assets/images/photos/bar-talk-speaker.webp" alt="Supriyo Saha speaking at a public science event"', 'assets/media/icecube-dawn.webp" alt="IceCube Observatory beneath the Antarctic night sky"')
home = home.replace('A public science talk</figcaption>', 'At the South Pole / IceCube Observatory</figcaption>')
home = home.replace('assets/media/icecube.webp', 'assets/media/icecube-dawn.webp').replace('assets/media/optogenetics.webp', 'assets/media/neuron-culture.webp')
page('index.html', 'Science communication for curious minds', 'Science films, talks and school programmes by 50 Shades of Science, founded by Supriyo Saha.', home)

science = intro('SCIENCE / THE QUESTIONS', 'Follow the question.', 'We explore science across fields, with a focus on what we know, how we know it, and what remains open.') + '''<section class="section wrap"><div class="topic-grid">'''+card('THE UNIVERSE', 'Cosmology & the early universe', 'How did the universe begin to take shape? Follow the evidence from light, matter, and the large-scale cosmos.')+card('THE UNSEEN', 'Dark matter', 'A question about gravity, galaxies, and the missing mass we can infer but have not yet identified.')+card('PARTICLES', 'Neutrinos & IceCube', 'Ghostlike particles cross matter almost unnoticed. Antarctic ice gives researchers a way to catch rare traces.')+card('LIFE', 'Brains, cells & optogenetics', 'How light-sensitive tools help researchers study living circuits with remarkable precision.')+card('TOOLS', 'AI & scientific discovery', 'Where machine learning can help scientists find patterns—and why interpretation still matters.')+card('METHOD', 'How science knows', 'Models, measurements, uncertainty, and the habit of changing our minds when the evidence changes.')+'''</div></section>''' + section('NEXT STEP', 'See the ideas in motion.', '<p>Watch our short explainers, then invite us to unpack a topic live for your audience.</p>'+link('Explore videos', 'videos.html'))
page('science.html', 'Explore science', 'Explore cosmology, dark matter, neutrinos, biology, AI and the scientific method with 50 Shades of Science.', science)

videos = intro('FILMS / VISUAL EXPLAINERS', 'Watch an idea unfold.', 'Short, visual science stories. Press play when you are ready; the films keep their original audio.') + '''<section class="video-list wrap"><article class="video-entry" id="icecube"><div class="video-frame"><video controls preload="none" playsinline poster="assets/media/icecube.webp" aria-label="IceCube neutrino explainer video"><source src="assets/media/icecube.mp4" type="video/mp4">Your browser does not support video.</video></div><div class="video-copy">'''+eyebrow('PHYSICS · 01')+'''<h2>IceCube: catching ghost particles</h2><p>Neutrinos almost never interact with matter. Deep in Antarctic ice, rare flashes of light offer a way to trace where some of them came from.</p><p class="meta">Vertical reel · 62 seconds</p></div></article><article class="video-entry" id="optogenetics"><div class="video-frame"><video controls preload="none" playsinline poster="assets/media/optogenetics.webp" aria-label="Optogenetics explainer video"><source src="assets/media/optogenetics.mp4" type="video/mp4">Your browser does not support video.</video></div><div class="video-copy">'''+eyebrow('BIOLOGY · 02')+'''<h2>Optogenetics: biology meets light</h2><p>A visual explainer on light-sensitive cells and the experiments that let researchers probe living neural circuits.</p><p class="meta">Vertical reel · 85 seconds</p></div></article></section>''' + section('MORE TO COME', 'Questions move us forward.', '<p>New films will appear here as they are made. Follow the project for the latest releases.</p><a class="text-link" href="https://www.instagram.com/50_shades_of_science/" target="_blank" rel="noopener noreferrer">Follow on Instagram ↗</a>')
videos = videos.replace('PHYSICS · 01', '2026 NOBEL PHYSICS · 01').replace('BIOLOGY · 02', '2026 NOBEL MEDICINE · 02')
videos = videos.replace('<p class="meta">Vertical reel · 62 seconds</p>', '<p class="meta">Vertical reel · 62 seconds</p><a class="text-link" href="https://www.nsf.gov/mps/updates/2026-nobel-prize-physics-awarded-nsf-icecube-neutrino" target="_blank" rel="noopener noreferrer">Prize background at NSF ↗</a>')
videos = videos.replace('<p class="meta">Vertical reel · 85 seconds</p>', '<p class="meta">Vertical reel · 85 seconds</p><a class="text-link" href="https://research-and-innovation.ec.europa.eu/news/all-research-and-innovation-news/eu-funded-researcher-peter-hegemann-wins-2026-nobel-prize-physiology-or-medicine-2026-10-05_en" target="_blank" rel="noopener noreferrer">Prize background at the European Commission ↗</a>')
page('videos.html', 'Science videos', 'Watch visual science explainers about IceCube, neutrinos, optogenetics and more.', videos)

schools = intro('FOR SCHOOLS / GRADES 8–12', 'A classroom full of questions.', 'Engaging talks and workshops designed to make students curious about evidence, ideas, and the people who investigate them.') + '''<section class="section wrap"><div class="section-heading">'''+eyebrow('WHAT WE CAN EXPLORE')+'''<h2>Start with a question.</h2></div><div class="three-grid">'''+card('SPACE', 'Our changing universe', 'The Big Bang, galaxies, black holes, dark matter, and how astronomers observe the distant universe.')+card('LIFE & MIND', 'The living world', 'Cells, the brain, and the methods scientists use to study biological systems.')+card('FUTURE TOOLS', 'AI and discovery', 'How scientists use data and models, with room to discuss uncertainty and responsible interpretation.')+'''</div></section>''' + section('FORMATS', 'Built for your students.', '<div class="detail-list"><div><strong>Interactive talk</strong><p>A visual, question-led session followed by open discussion.</p></div><div><strong>Workshop</strong><p>Small-group activities that turn a concept into an investigation.</p></div><div><strong>Series or science day</strong><p>Multiple sessions shaped around a theme, age group, or school goal.</p></div></div><p>Sessions can be adapted for grades 8–12. Duration, group size, and topic are agreed with each school.</p>') + '''<section class="photo-band wrap"><img src="assets/images/photos/bar-talk-audience.webp" alt="Audience engaged in a live science talk" loading="lazy"><div>'''+eyebrow('THE EXPERIENCE')+'''<h2>Participation over passive listening.</h2><p>Students are invited to make predictions, ask questions, and connect a scientific claim to the evidence behind it.</p></div></section>''' + section('BOOK A SESSION', 'Tell us about your school.', '<p>Share your city, student group, preferred date, and the questions your students are asking.</p>'+link('Enquire about a school programme', 'contact.html?interest=school', 'button'))
page('school-programmes.html', 'School programmes', 'Science talks and workshops for grades 8–12, tailored to schools by 50 Shades of Science.', schools)

future = intro('FUTURE SCIENTISTS / PROGRAMME VISION', 'Give curiosity a method.', 'Future Scientists is a developing programme idea for students who want to go beyond memorising answers and learn how to investigate questions.') + '''<section class="quote-band"><div class="wrap"><blockquote>“A future scientist is not someone who knows everything. It is someone who knows how to ask, test, and keep learning.”</blockquote></div></section>''' + section('THE APPROACH', 'From wonder to investigation.', '<div class="detail-list numbered"><div><strong>01 · Ask</strong><p>Turn a broad curiosity into a question that can be explored.</p></div><div><strong>02 · Test</strong><p>Use observation, models, and simple experiments to compare ideas.</p></div><div><strong>03 · Explain</strong><p>Communicate what the evidence says, what it does not, and what comes next.</p></div></div>') + section('WHO IT IS FOR', 'A pathway for curious students.', '<p>The programme is being shaped for school-age learners and educators. Format, duration, and delivery can be developed with partner schools; no fixed cohort or outcome is claimed yet.</p>'+link('Discuss a pilot', 'contact.html?interest=future', 'button'))
page('future-scientists.html', 'Future Scientists Programme', 'A developing learning programme focused on curiosity, evidence and scientific thinking.', future)

csr = intro('CSR & PARTNERSHIPS', 'Make science access measurable.', 'We work with partners to design science engagement that is useful to students, practical for schools, and honest about its results.') + section('A POSSIBLE PILOT', 'A partnership designed to learn.', '<p>The outline below is an <strong>illustrative proposal</strong>, not a completed project or a claim of existing reach.</p><div class="pilot-grid"><div><span>20</span><small>schools, illustrative</small></div><div><span>3k–5k</span><small>students, illustrative</small></div><div><span>8–12</span><small>grade range</small></div><div><span>Mumbai</span><small>example geography</small></div></div>') + section('HOW IT COULD WORK', 'A clear route from plan to evidence.', '<div class="detail-list numbered"><div><strong>01 · Co-design</strong><p>Agree the learning goals, school needs, delivery format, and access considerations.</p></div><div><strong>02 · Deliver</strong><p>Run talks, workshops, or a multi-session programme with room for questions and feedback.</p></div><div><strong>03 · Measure</strong><p>Track participation, collect student and teacher feedback, and compare learning indicators where appropriate.</p></div><div><strong>04 · Report</strong><p>Share an honest summary of what worked, what changed, and what to improve.</p></div></div>') + section('LET US BUILD IT', 'Start with your priorities.', '<p>Tell us about your target schools, geography, timeline, and reporting needs. We can shape a pilot scope together.</p>'+link('Discuss a partnership', 'contact.html?interest=csr', 'button'))
page('csr-partnerships.html', 'CSR and partnerships', 'Explore a measurable science education partnership with 50 Shades of Science, including an illustrative school pilot.', csr)

about = intro('ABOUT / THE PEOPLE', 'Science, with a human voice.', '50 Shades of Science is an independent science communication project founded by Supriyo Saha.') + '''<section class="about-grid wrap"><img src="assets/media/supriyo.webp" alt="Portrait of Supriyo Saha" loading="lazy"><div>'''+eyebrow('FOUNDER')+'''<h2>Supriyo Saha</h2><p>Supriyo is a PhD researcher in cosmology at the Tata Institute of Fundamental Research (TIFR), Mumbai. He brings a researcher's curiosity and a communicator's instinct to science stories for a wider audience.</p><p>Through 50 Shades of Science, he creates explainers and live experiences spanning physics, biology, AI, and the broader process of discovery.</p><p class="fine-print">50 Shades of Science is an independent project. Institutional affiliation identifies the founder's research position and does not imply TIFR endorsement.</p>'''+link('Explore his research', 'research.html')+'''</div></section>''' + section('WHY THIS EXISTS', 'Understanding should feel possible.', '<p>A good explanation respects both the science and the audience. We aim to make difficult ideas accessible without pretending every question has a simple answer.</p>') + '''<section class="gallery wrap"><img src="assets/images/photos/bar-talk-room.webp" alt="People gathered for a public science talk" loading="lazy"><img src="assets/images/photos/bar-talk-cosmic-slide.webp" alt="Cosmology being explained at a live event" loading="lazy"></section>'''
page('about.html', 'About 50 Shades of Science', 'Meet Supriyo Saha and the independent science communication project 50 Shades of Science.', about)

research = intro('RESEARCH / FOUNDER BACKGROUND', 'A researcher’s eye for the cosmos.', 'Supriyo Saha is a PhD researcher in cosmology at TIFR Mumbai. That work informs the care we bring to communicating science.') + section('THE FIELD', 'How did the universe become what we see?', '<p>Cosmology studies the history and structure of the universe using observations, mathematical models, and physical theory. Questions about the early universe and dark matter are part of this larger search.</p><p>This page describes Supriyo’s research field. Specific papers, discoveries, and institutional projects will be listed only when verified and approved for publication.</p>') + section('BEYOND ONE DISCIPLINE', 'Research informs the method, not the limits.', '<p>Our communication work ranges beyond cosmology—from biology to AI—while keeping the same habits of clarity, evidence, and curiosity.</p>'+link('Explore our science topics', 'science.html'))
page('research.html', 'Research background', 'Learn about founder Supriyo Saha’s cosmology research background and its role in 50 Shades of Science.', research)

contact = intro('CONTACT / BOOK', 'Let’s make something clear.', 'Tell us about the audience, the question, and the experience you want to create. We will respond by email.') + '''<section class="contact-layout wrap"><div class="contact-aside">'''+eyebrow('DIRECT EMAIL')+f'''<h2>Prefer to write directly?</h2><p><a href="mailto:{EMAIL}">{EMAIL}</a></p><p>For a faster reply, include your city, audience, approximate group size, and preferred date.</p><div class="contact-note"><strong>How this form works</strong><p>Submitting opens your email app with a prepared message. Review and send it there. No information is stored on this website.</p></div></div><form id="booking-form" class="booking-form"><div class="field-row"><label>Your name <span>*</span><input name="name" autocomplete="name" required></label><label>Email <span>*</span><input name="email" type="email" autocomplete="email" required></label></div><label>Organisation or school<input name="organisation" autocomplete="organization"></label><div class="field-row"><label>What are you interested in? <span>*</span><select name="interest" required><option value="">Select an option</option><option value="School programme">School programme</option><option value="Future Scientists">Future Scientists</option><option value="CSR / partnership">CSR / partnership</option><option value="Public talk">Public talk</option><option value="Film / collaboration">Film / collaboration</option><option value="Other">Other</option></select></label><label>City / location<input name="location" autocomplete="address-level2"></label></div><div class="field-row"><label>Audience and approximate size<input name="audience" placeholder="e.g. Grade 9, around 80 students"></label><label>Preferred date or timeframe<input name="timeframe" placeholder="e.g. late November"></label></div><label>Tell us more <span>*</span><textarea name="message" rows="6" required placeholder="What question, topic, or goal is on your mind?"></textarea></label><button class="button" type="submit">Prepare email enquiry ↗</button><p id="form-status" class="form-status" role="status" aria-live="polite"></p></form></section>'''
page('contact.html', 'Contact and book', 'Enquire about science talks, school programmes, videos, and CSR partnerships with 50 Shades of Science.', contact)

(ROOT / 'robots.txt').write_text('User-agent: *\nAllow: /\nSitemap: https://supriyosaha1.github.io/50-shades-of-science/sitemap.xml\n', encoding='utf-8')
(ROOT / 'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' + ''.join('<url><loc>https://supriyosaha1.github.io/50-shades-of-science/' + ('' if key == 'index.html' else key) + '</loc></url>\n' for key in ['index.html','science.html','videos.html','school-programmes.html','future-scientists.html','csr-partnerships.html','about.html','research.html','contact.html']) + '</urlset>\n', encoding='utf-8')
print('Generated 9 HTML pages.')
